import type { TestCatalogEntry } from "./types";

/** Public content transcribed from the three supplied HTML files, never their scripts. */
export const SECOND_CONDITIONAL: TestCatalogEntry = {
  id: "second-conditional", version: 1, level: "b1", category: "grammar",
  title: "Second conditional", subtitle: "Second conditional: Unreal situations",
  cover: { src: "/images/tests/second-conditional-v1.webp", width: 1200, height: 600,
    alt: "B1 second conditional: I'm glad to be poor. If I was rich, I would be like him!" },
  exercises: [
    { id: "exercise-1", number: 1, instruction: "Choose the correct form to complete the sentences below.", questions: [
      { id: "q1", before: "I'd give you her number if I ", after: " it.", options: ["would have", "had", "have"] },
      { id: "q2", before: "If I won the lottery, I think I ", after: " my job.", options: ["didn't give up", "wouldn't give up", "hadn't given up"] },
      { id: "q3", before: "Who ", after: " date if you could date anyone in the world?", options: ["had you", "would you", "did you"] },
      { id: "q4", before: "If everybody in the world ", after: " one dollar, we'd finish the world's problems.", options: ["would donate", "donated", "donate"] },
      { id: "q5", before: "If you ", after: " my wife, I'd make you the happiest woman on earth.", options: ["were", "did", "would be"] },
      { id: "q6", before: "I ", after: " about that if I were you.", options: ["didn't worry", "wouldn't worry", "hadn't worried"] },
      { id: "q7", before: "If you told grandpa the truth, he ", after: " a heart attack.", options: ["might have", "will have", "had"] },
      { id: "q8", before: "I wouldn't call unless I ", after: " a real emergency.", options: ["will have", "would have", "had"] },
      { id: "q9", before: "You ", after: " to spend so much time tidying your house if you didn't have so much stuff.", options: ["hadn't had", "didn't have", "wouldn't have"] },
      { id: "q10", before: "If you ", after: " so much noise, I could concentrate.", options: ["won't make", "didn't make", "wouldn't make"] },
    ] },
    { id: "exercise-2", number: 2, instruction: "Choose the correct form for each gap below. Where indicated, choose TWO correct options.", questions: [
      { id: "q1", before: "If I ", after: " you, I wouldn't trust him.", options: ["was", "were", "did"] },
      { id: "q2", before: "If we didn't take precautions, we ", after: " hurt.", options: ["can get", "might get", "would get"], kind: "multiple", selectionCount: 2 },
      { id: "q3", before: "", after: "", prompt: "You ___ healthier if you ___ a bit of weight.", options: ["felt / would lose", "would feel / would lose", "would feel / lost"] },
      { id: "q4", before: "If we sold the house, we ", after: " much right now.", options: ["didn't get", "wouldn't get", "won't get"] },
      { id: "q5", before: "Would you mind if I ", after: " the window?", options: ["open", "would open", "opened"] },
      { id: "q6", before: "", after: "", prompt: "I ___ him if he ___ me to help him.", options: ["helped / 'd allow", "'d help / allowed", "'d help / allow"] },
      { id: "q7", before: "If you painted the walls white, the living room ", after: " bigger.", options: ["would look", "looked", "had looked"] },
      { id: "q8", before: "If I was healthier, we ", after: " more often.", options: ["could travel", "travelled", "might travel"], kind: "multiple", selectionCount: 2 },
      { id: "q9", before: "", after: "", prompt: "What kind of job ___ to have if you ___ a teacher?", options: ["would you like / weren't", "would you like / wasn't", "did you like / wouldn't be"] },
      { id: "q10", before: "", after: "", prompt: "If drugs ___ legal, the world ___ safer.", options: ["'d be / were", "'d be / would be", "were / would be"] },
    ] },
    { id: "exercise-3", number: 3, instruction: "Fill in the gaps with the verbs in brackets using would/wouldn't or the past simple to complete the second conditional sentences.", questions: [
      { id: "q1", kind: "text", before: "Where ", after: " (you/travel) to if you …?", options: [] },
      { id: "q2", kind: "text", before: "… if you ", after: " (can) go anywhere?", options: [] },
      { id: "q3", kind: "text", before: "What ", after: " (you/do) if you …?", options: [] },
      { id: "q4", kind: "text", before: "… if you ", after: " (be) in my situation?", options: [] },
      { id: "q5", kind: "text", before: "If she ", after: " (know), she …", options: [] },
      { id: "q6", kind: "text", before: "… she ", after: " (tell) you.", options: [] },
      { id: "q7", kind: "text", before: "I ", after: " (have) a better job if I …", options: [] },
      { id: "q8", kind: "text", before: "… if I ", after: " (speak) English better.", options: [] },
      { id: "q9", kind: "text", before: "I ", after: " (never/forgive) you if I …", options: [] },
      { id: "q10", kind: "text", before: "… if I ", after: " (not be) your friend.", options: [] },
      { id: "q11", kind: "text", before: "I ", after: " (be) happier if I …", options: [] },
      { id: "q12", kind: "text", before: "… if I ", after: " (have) more time.", options: [] },
      { id: "q13", kind: "text", before: "If you ", after: " (find) a wallet with a lot of money in it, …", options: [] },
      { id: "q14", kind: "text", before: "… what ", after: " (you/do)?", options: [] },
      { id: "q15", kind: "text", before: "If she ", after: " (not criticise) people so often, …", options: [] },
      { id: "q16", kind: "text", before: "… she ", after: " (have) more friends.", options: [] },
      { id: "q17", kind: "text", before: "If you ", after: " (get) lost, …", options: [] },
      { id: "q18", kind: "text", before: "… I ", after: " (go) to the end of the world to find you.", options: [] },
      { id: "q19", kind: "text", before: "He ", after: " (not travel) alone if he …", options: [] },
      { id: "q20", kind: "text", before: "… if he ", after: " (not have) his parents' permission.", options: [] },
    ], passage: [
      [{ text: "Where " }, { questionId: "q1" }, { text: " (you/travel) to if you " }, { questionId: "q2" }, { text: " (can) go anywhere?" }],
      [{ text: "What " }, { questionId: "q3" }, { text: " (you/do) if you " }, { questionId: "q4" }, { text: " (be) in my situation?" }],
      [{ text: "If she " }, { questionId: "q5" }, { text: " (know), she " }, { questionId: "q6" }, { text: " (tell) you." }],
      [{ text: "I " }, { questionId: "q7" }, { text: " (have) a better job if I " }, { questionId: "q8" }, { text: " (speak) English better." }],
      [{ text: "I " }, { questionId: "q9" }, { text: " (never/forgive) you if I " }, { questionId: "q10" }, { text: " (not be) your friend." }],
      [{ text: "I " }, { questionId: "q11" }, { text: " (be) happier if I " }, { questionId: "q12" }, { text: " (have) more time." }],
      [{ text: "If you " }, { questionId: "q13" }, { text: " (find) a wallet with a lot of money in it, what " }, { questionId: "q14" }, { text: " (you/do)?" }],
      [{ text: "If she " }, { questionId: "q15" }, { text: " (not criticise) people so often, she " }, { questionId: "q16" }, { text: " (have) more friends." }],
      [{ text: "If you " }, { questionId: "q17" }, { text: " (get) lost, I " }, { questionId: "q18" }, { text: " (go) to the end of the world to find you." }],
      [{ text: "He " }, { questionId: "q19" }, { text: " (not travel) alone if he " }, { questionId: "q20" }, { text: " (not have) his parents' permission." }],
    ] },
  ],
};
